### ISSUE TITLE
todo: review and implement 12 month worth of db updates

### ISSUE THREAD

**Issue by Sarjuuk** [Sarjuuk/aowow#191]
to 15. 2. 2020:
- [x] ~~https://github.com/TrinityCore/TrinityCore/commit/c574972cb2d000caacd155ddd32af425bed259ee~~
    table not referenced
- [x] https://github.com/TrinityCore/TrinityCore/commit/6c85964065dc2b2d397904d79755eacc43a8ab0d
    1ff81ab07c3c0d5d892692c9b65b0a3d2319ccf1

to 15. 9. 2019:
- [x] ~~https://github.com/TrinityCore/TrinityCore/commit/677663139cd~~
    field not referenced

to 16. 8. 2019:
- [x] https://github.com/TrinityCore/TrinityCore/commit/915f8a9d2c2
    eaa982e5b349b6421a857f007cef9d313f2e7230
- [x] ~~https://github.com/TrinityCore/TrinityCore/commit/45bc91c238d~~
- [x] ~~https://github.com/TrinityCore/TrinityCore/commit/a5e73e41c0e~~
    i never implemented pooling :(

to 15. 7. 2019:
- [x] https://github.com/TrinityCore/TrinityCore/commit/d5fb0a30ec6
    48552a97ab8c04df64fe59fd0556c0c3aeefa6d0

to 15. 4. 2019:
- [x] https://github.com/TrinityCore/TrinityCore/commit/5ed77113b63
    d4c0c0535a689ccf58d384b1f9a24245cb81b5dd

older:
- [x] ~~https://github.com/TrinityCore/TrinityCore/commit/d1c3ee95796~~
    field not referenced
- [x] ~~https://github.com/TrinityCore/TrinityCore/commit/592516ae69d~~
    field not referenced
- [x] ~~https://github.com/TrinityCore/TrinityCore/commit/743980a6255~~
    table not in use
- [x] https://github.com/TrinityCore/TrinityCore/commit/7634a57f64a
    243429bf68c225f4e7cfae6b7ee6dea8857dfb1c
- [x] https://github.com/TrinityCore/TrinityCore/commit/8edea4a3c29
    bc18ca174cb28f054dac51c76016b34d9c0a1bea
- [x] ~~https://github.com/TrinityCore/TrinityCore/commit/2f5403d4af3~~
    already implemented
- [x] https://github.com/TrinityCore/TrinityCore/commit/352c4a4c680
    d3c5011694d538034e3fead3dbbb01ae08ea65b9
- [x] https://github.com/TrinityCore/TrinityCore/commit/bf3ab6d9c43
    16bd59e0cc727490607db3672aff5468d757b61e

**Comment by jackpoz** [comment]
https://github.com/Sarjuuk/aowow/compare/master...TrinityCore:master might help you as it contains support to latest 3.3.5 and fixes some issues here and there (i.e. Spell Effect Create Item showing the wrong item)

**Comment by Sarjuuk** [comment]
thanks, i'm already cherry-picking :D

**Comment by Sarjuuk** [comment]
..and we are up to date again!
